name: ServerCore
version: '1.0'
main: com.mills.core.Main
api-version: '1.21'
commands:
  fly:
  heal:
  feed:
  ptime:
  pweather:
  gmc:
  gms:
  gmsp:
  gma:
  gamemode:
  enchant:
  craft:
    aliases:
      - workbench
  fix:
  speed:
  enderchest:
    aliases:
      - echest
  top:
  hat:
  clearinventory:
  seen:
  ping:
  nick:
    aliases:
      - nickname
  near:
  corereload:
  chatcolor:
  bal:
  economy:
  store:
  rename:
  back:
  setspawn:
  spawn:
  teleport:
    aliases:
      - tp
  teleporthere:
    aliases:
      - tphere
  sethome:
  homes:
  home:
  movehome:
  deletehome:
    aliases:
      - delhome
  setwarp:
  warp:
  warps:
  deletewarp:
    aliases:
      - delwarp
  anvil:
  offlineteleport:
    aliases:
      - offlinetp
      - otp
  playtime:
  tpa:
  tpaaccept:
  tpadeny:
  tpatoggle:
  discord:
  baltop:
depend: [Vault]


